CREATE USER IF NOT EXISTS sa PASSWORD 'root';
ALTER USER sa ADMIN TRUE;

-- CREATE TABLE department
-- (
--     id            BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
--     code          VARCHAR(64) UNIQUE                NOT NULL,
--     name          VARCHAR(64)                       NOT NULL,
--     parent_id     BIGINT                            NULL,
--     register_date DATE                              NOT NULL,
--     version       INT         DEFAULT 0             NOT NULL
-- );
--
-- CREATE TABLE employee
-- (
--     id              BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
--     no              VARCHAR(64) UNIQUE                NOT NULL,
--     name            VARCHAR(64)                       NOT NULL,
--     gender          TINYINT(1)                        NOT NULL,
--     birth           DATE                              NOT NULL,
--     mobile          VARCHAR(32)                       NOT NULL,
--     email           VARCHAR(64)                       NOT NULL,
--     department_code VARCHAR(64)                       NOT NULL,
--     title           VARCHAR(64)                       NOT NULL,
--     onboard_date    DATE                              NOT NULL,
--     departure_date  DATE                              NOT NULL,
--     version         INT DEFAULT 0                     NOT NULL
-- );
--
-- CREATE TABLE employee_extra_info
-- (
--     id           BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
--     employee_id  BIGINT                            NOT NULL,
--     introduction VARCHAR(64)                       NOT NULL,
--     blog_uri     VARCHAR(64)                       NOT NULL,
--     salary       DECIMAL(10, 2)                    NOT NULL,
-- );
--
-- CREATE UNIQUE INDEX ux_employee ON employee_extra_info (employee_id);
--
-- CREATE TABLE ref_department_manager
-- (
--     id            BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
--     department_id BIGINT                            NOT NULL,
--     employee_id   BIGINT                            NOT NULL
-- );
--
-- CREATE UNIQUE INDEX ux_department_employee ON ref_department_manager (department_id, employee_id);
